from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from app.config import settings
from app.models.request import GenerateBatchRequest
from app.models.response import GenerateBatchResponse
from app.services.llm_service import generate_scenarios, stream_generate_scenarios

router = APIRouter()


@router.post("/scenarios/generate-batch", response_model=GenerateBatchResponse)
async def generate_batch(request: GenerateBatchRequest):
    """Generate a batch of personalized safety scenarios for children.

    Calls the LLM once to generate all scenarios based on child info and config.
    """
    # Validate difficulty against runtime config
    if request.config.difficulty > settings.MAX_DIFFICULTY:
        raise HTTPException(
            status_code=422,
            detail=f"difficulty must be between 1 and {settings.MAX_DIFFICULTY}",
        )

    return await generate_scenarios(request)


@router.post("/scenarios/generate-stream")
async def generate_stream(request: GenerateBatchRequest):
    """Stream personalized safety scenarios for children.

    Returns a stream of JSON chunks as they are generated by the LLM.
    Useful for UI progress indicators.
    """
    # Validate difficulty
    if request.config.difficulty > settings.MAX_DIFFICULTY:
        raise HTTPException(
            status_code=422,
            detail=f"difficulty must be between 1 and {settings.MAX_DIFFICULTY}",
        )

    return StreamingResponse(
        stream_generate_scenarios(request),
        media_type="text/event-stream",
    )
